### PR TITLE
Multilevel navbar

### LINKED ISSUE #38: Demonstrate dynamic changes to page for navigation using only CSS

### LINKED ISSUE #49: On smartphone view, use "All Articles" as inspiration for the "Parents & Caregivers" page so that it is clickable - use the wireframes, too!

### LINKED ISSUE #55: On smartphone view, update the icons to the new icon set

### LINKED ISSUE #57: Start creating demo site for easy access - if it's too time-consuming, then feel free to drop this and let me know!

### LINKED ISSUE #60: Change the COVID-19 icon to the virus icon

### LINKED ISSUE #61: Change navigation to be based on The Washington Post

### LINKED ISSUE #64: On all current pages, change the green color to IoGT green, and blue color to IoGT blue; look at Laurie's branding guidelines in Slack for help

### LINKED ISSUE #70: Wait for Laurie's new icons (sending from graphic designer); make icons bigger; bold the text

### LINKED ISSUE #78: Edit articles home page such that within each row of articles, the titles start on the same level, the subtitles start on the same level, and the color bars at the bottom start on the same level

### PR DESCRIPTION
**Pull request by michaelclapham**

### CODE REVIEW

**Comment by jtoaha** [comment]
**Multilevel Navbar:** 
- Added designs and polished up multilevel navigation CSS  for feature, mobile, tablet and desktop. 
- Changed some icons (added svg files) / adjusted logo size for tablet and desktop
- Restructured html to allow more logical viewing of menu items (i.e. "–" sign for parent topics persists when hovering on sub-subtopics and sub-sub-subtopics)
- For nav bar items, added a CSS class of "navbaritem1" "navbaritem2" instead of "youth" and "parents" to make it easier for CSS values to apply to whatever names of navbar items passed. _(Side note: just discovered there exists zero-runtime CSS, such as [Linaria](https://www.npmjs.com/package/linaria-preact), which might solve this problem and allow more dynamic creation of css - and might allow existing css written directly in preact to work when javascript is turned off since it creates the css files at build time)_


**Articles Component:** 
- Currently working on factoring  in Michael's suggestion of unifying Articles prop types.  To do so, working on refactoring Article Listing to be a little less hardcoded (work with variables - so we can change up more easily when bringing in info from backend). Still in progress. But in the process, created a types folder, updated Article Listing CSS media queries to be based on screen size instead of device size and renamed components to ArticleThumbnail and ArticleListing.

**Comment by michaelclapham** [comment]
Could you remove the .cache folder from this PR and add it to the .gitignore file?

**Comment by isedwards** [comment]
@jtoaha this branch had several conflicts at the moment. Would you like to take a look at resolving them?

Let me know if you'd like some help with the process for working through resolving conflicts.

**Comment by jtoaha** [comment]
Sure, I should be able to resolve it. Thanks so much. Just taking care of multiple issues, made commits to keep the changes a bit separate. I still have to do the new updates for the navbar. Once I do that I'll follow up.

Note: The above commits mainly include changes to the navbar as well as to articles. Also added the Linaria library for zero run-time CSS for future use.

**Comment by jtoaha** [comment]
Resolved Merge Conflict. As expected, some of our stylings overlapped. So adjusted CSS as needed.  Also for the Login Modal, carried Desktop styling into Tablet mode. And, for a more seamless experience, used javascript to close out desktop/ tablet Login Modal (if it's open) when switching to Feature or Mobile mode. 

Our combined changes can be viewed at: [https://unicef-iogt-pwa-v2.web.app/](https://unicef-iogt-pwa-v2.web.app/)

Note: Can be merged into develop. But preferable if branch was not deleted. Navbar changes still need to be done. Next thing I'll be working on over the next day

**Pull request merged**
